before_install:
  - sudo apt-get -qq update
  - sudo apt-get install swig

language: java
jdk:
  - openjdk11

notifications:
  email: false

script:
  - mkdir dependencies

  # Install tensor master
  - cd dependencies
  - git clone https://github.com/amodeus-science/tensor.git
  - cd tensor
  - mvn install -DskipTests=True
  - cd .. && cd ..

  # Install AMoDeus master
  - cd dependencies
  - git clone https://github.com/amodeus-science/amodeus.git
  - cd amodeus
  - mvn install -DskipTests=True
  - cd .. && cd ..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:dependencies/amodeus/resources/3rdparty/glpk/lib/jni

  # Test amod
  - mvn install -DskipTests=true -B -V -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true
  - mvn test -B -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true
